import { type ComponentType, lazy } from 'react';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type MdxComponent = ComponentType<any>;

/**
 * MDX content registry — auto-generated + hand-written pages.
 *
 * To add rich docs for a component, create `content/components/<slug>.mdx`
 * and add the lazy import here. Components without an entry fall back to
 * the auto-generated template.
 */
const mdxPages: Record<string, () => Promise<{ default: MdxComponent }>> = {
  'button': () => import('./components/button.mdx'),
  'input': () => import('./components/input.mdx'),
  'select': () => import('./components/select.mdx'),
  'textarea': () => import('./components/textarea.mdx'),
  'checkbox': () => import('./components/checkbox.mdx'),
  'radio': () => import('./components/radio.mdx'),
  'badge': () => import('./components/badge.mdx'),
  'tag': () => import('./components/tag.mdx'),
  'price': () => import('./components/price.mdx'),
  'quantity-selector': () => import('./components/quantity-selector.mdx'),
  'rating': () => import('./components/rating.mdx'),
  'skeleton': () => import('./components/skeleton.mdx'),
  'empty-state': () => import('./components/empty-state.mdx'),
  'divider': () => import('./components/divider.mdx'),
  'avatar': () => import('./components/avatar.mdx'),
  'card': () => import('./components/card.mdx'),
  'modal': () => import('./components/modal.mdx'),
  'drawer': () => import('./components/drawer.mdx'),
  'toast': () => import('./components/toast.mdx'),
  'tooltip': () => import('./components/tooltip.mdx'),
  'accordion': () => import('./components/accordion.mdx'),
  'tabs': () => import('./components/tabs.mdx'),
  'breadcrumb': () => import('./components/breadcrumb.mdx'),
  'header': () => import('./components/header.mdx'),
  'announcement-bar': () => import('./components/announcement-bar.mdx'),
  'footer': () => import('./components/footer.mdx'),
  'mobile-menu': () => import('./components/mobile-menu.mdx'),
  'search-overlay': () => import('./components/search-overlay.mdx'),
  'cart-drawer': () => import('./components/cart-drawer.mdx'),
  'product-card': () => import('./components/product-card.mdx'),
  'product-gallery': () => import('./components/product-gallery.mdx'),
  'product-info': () => import('./components/product-info.mdx'),
  'variant-selector': () => import('./components/variant-selector.mdx'),
  'product-form': () => import('./components/product-form.mdx'),
  'product-slider': () => import('./components/product-slider.mdx'),
  'collection-hero': () => import('./components/collection-hero.mdx'),
  'collection-grid': () => import('./components/collection-grid.mdx'),
  'filters': () => import('./components/filters.mdx'),
  'pagination': () => import('./components/pagination.mdx'),
  'artist-profile': () => import('./components/artist-profile.mdx'),
  'process-timeline': () => import('./components/process-timeline.mdx'),
  'certificate': () => import('./components/certificate.mdx'),
  'collection-story': () => import('./components/collection-story.mdx'),
  'masonry-gallery': () => import('./components/masonry-gallery.mdx'),
  'hero': () => import('./components/hero.mdx'),
  'newsletter': () => import('./components/newsletter.mdx'),
  'testimonials': () => import('./components/testimonials.mdx'),
  'coming-soon': () => import('./components/coming-soon.mdx'),
  'button-group': () => import('./components/button-group.mdx'),
  'icon-button': () => import('./components/icon-button.mdx'),
  'close-button': () => import('./components/close-button.mdx'),
  'toggle': () => import('./components/toggle.mdx'),
  'fab': () => import('./components/fab.mdx'),
  'alert': () => import('./components/alert.mdx'),
  'progress': () => import('./components/progress.mdx'),
  'spinner': () => import('./components/spinner.mdx'),
  'stat': () => import('./components/stat.mdx'),
  'data-table': () => import('./components/data-table.mdx'),
  'data-list': () => import('./components/data-list.mdx'),
  'timeline-primitive': () => import('./components/timeline-primitive.mdx'),
  'link': () => import('./components/link.mdx'),
  'popover': () => import('./components/popover.mdx'),
  'hover-card': () => import('./components/hover-card.mdx'),
  'dropdown-menu': () => import('./components/dropdown-menu.mdx'),
  'context-menu': () => import('./components/context-menu.mdx'),
  'command-palette': () => import('./components/command-palette.mdx'),
  'steps': () => import('./components/steps.mdx'),
  'carousel': () => import('./components/carousel.mdx'),
  'scroll-area': () => import('./components/scroll-area.mdx'),
  'lightbox': () => import('./components/lightbox.mdx'),
  'switch': () => import('./components/switch.mdx'),
  'slider': () => import('./components/slider.mdx'),
  'combobox': () => import('./components/combobox.mdx'),
  'date-picker': () => import('./components/date-picker.mdx'),
  'color-picker': () => import('./components/color-picker.mdx'),
  'file-upload': () => import('./components/file-upload.mdx'),
  'pin-input': () => import('./components/pin-input.mdx'),
  'tags-input': () => import('./components/tags-input.mdx'),
  'segmented-control': () => import('./components/segmented-control.mdx'),
  'field-wrapper': () => import('./components/field-wrapper.mdx'),
  'fieldset': () => import('./components/fieldset.mdx'),
  'inline-error': () => import('./components/inline-error.mdx'),
  'password-input': () => import('./components/password-input.mdx'),
  'number-input': () => import('./components/number-input.mdx'),
  'form': () => import('./components/form.mdx'),
  'popup': () => import('./components/popup.mdx'),
  'trust-badges': () => import('./components/trust-badges.mdx'),
  'payment-icons': () => import('./components/payment-icons.mdx'),
  'countdown': () => import('./components/countdown.mdx'),
  'urgency': () => import('./components/urgency.mdx'),
  'cookie-consent': () => import('./components/cookie-consent.mdx'),
  'social-proof': () => import('./components/social-proof.mdx'),
  'announcement-extended': () => import('./components/announcement-extended.mdx'),
  'cart-page': () => import('./components/cart-page.mdx'),
  'cart-line-item': () => import('./components/cart-line-item.mdx'),
  'cart-summary': () => import('./components/cart-summary.mdx'),
  'discount-field': () => import('./components/discount-field.mdx'),
  'free-shipping-bar': () => import('./components/free-shipping-bar.mdx'),
  'cart-upsell': () => import('./components/cart-upsell.mdx'),
  'cart-empty': () => import('./components/cart-empty.mdx'),
  'quick-view': () => import('./components/quick-view.mdx'),
  'sticky-atc': () => import('./components/sticky-atc.mdx'),
  'cart-note': () => import('./components/cart-note.mdx'),
  'gift-wrap': () => import('./components/gift-wrap.mdx'),
  'auth-forms': () => import('./components/auth-forms.mdx'),
  'password-reset': () => import('./components/password-reset.mdx'),
  'account-dashboard': () => import('./components/account-dashboard.mdx'),
  'order-history': () => import('./components/order-history.mdx'),
  'order-detail': () => import('./components/order-detail.mdx'),
  'address-book': () => import('./components/address-book.mdx'),
  'address-form': () => import('./components/address-form.mdx'),
  'wishlist': () => import('./components/wishlist.mdx'),
  'account-settings': () => import('./components/account-settings.mdx'),
  'article-card': () => import('./components/article-card.mdx'),
  'article-hero': () => import('./components/article-hero.mdx'),
  'article-body': () => import('./components/article-body.mdx'),
  'reading-progress': () => import('./components/reading-progress.mdx'),
  'table-of-contents': () => import('./components/table-of-contents.mdx'),
  'author-card': () => import('./components/author-card.mdx'),
  'category-nav': () => import('./components/category-nav.mdx'),
  'blog-sidebar': () => import('./components/blog-sidebar.mdx'),
  'share-buttons': () => import('./components/share-buttons.mdx'),
  'related-articles': () => import('./components/related-articles.mdx'),
  'comments': () => import('./components/comments.mdx'),
  'hero-section': () => import('./components/hero-section.mdx'),
  'featured-collection': () => import('./components/featured-collection.mdx'),
  'image-text': () => import('./components/image-text.mdx'),
  'multicolumn': () => import('./components/multicolumn.mdx'),
  'gallery-grid': () => import('./components/gallery-grid.mdx'),
  'lookbook': () => import('./components/lookbook.mdx'),
  'video-section': () => import('./components/video-section.mdx'),
  'brand-story': () => import('./components/brand-story.mdx'),
  'faq-section': () => import('./components/faq-section.mdx'),
  'contact-section': () => import('./components/contact-section.mdx'),
  'stats-section': () => import('./components/stats-section.mdx'),
  'logo-bar': () => import('./components/logo-bar.mdx'),
  'comparison-table': () => import('./components/comparison-table.mdx'),
  'shipping-info': () => import('./components/shipping-info.mdx'),
  'rich-text-section': () => import('./components/rich-text-section.mdx'),
  'material-library': () => import('./components/material-library.mdx'),
  'glaze-guide': () => import('./components/glaze-guide.mdx'),
  'technique-explainer': () => import('./components/technique-explainer.mdx'),
  'care-instructions': () => import('./components/care-instructions.mdx'),
  'dimensions': () => import('./components/dimensions.mdx'),
  'firing-info': () => import('./components/firing-info.mdx'),
  'workshop-listing': () => import('./components/workshop-listing.mdx'),
  'commission-form': () => import('./components/commission-form.mdx'),
  'makers-mark': () => import('./components/makers-mark.mdx'),
  'edition-badge': () => import('./components/edition-badge.mdx'),
  'certificate-details': () => import('./components/certificate-details.mdx'),
  'mega-menu': () => import('./components/mega-menu.mdx'),
  'bottom-nav': () => import('./components/bottom-nav.mdx'),
  'size-chart': () => import('./components/size-chart.mdx'),
  'back-in-stock': () => import('./components/back-in-stock.mdx'),
  'store-pickup': () => import('./components/store-pickup.mdx'),
  'subscription-option': () => import('./components/subscription-option.mdx'),
  'view-toggle': () => import('./components/view-toggle.mdx'),
  'collection-promo': () => import('./components/collection-promo.mdx'),
  'empty-collection': () => import('./components/empty-collection.mdx'),
  'artist-index': () => import('./components/artist-index.mdx'),
  'artist-card': () => import('./components/artist-card.mdx'),
  'exhibition-page': () => import('./components/exhibition-page.mdx'),
  'artist-statement': () => import('./components/artist-statement.mdx'),
  'review-summary': () => import('./components/review-summary.mdx'),
  'star-rating': () => import('./components/star-rating.mdx'),
  'star-input': () => import('./components/star-input.mdx'),
  'review-card': () => import('./components/review-card.mdx'),
  'review-highlights': () => import('./components/review-highlights.mdx'),
  'photo-reviews': () => import('./components/photo-reviews.mdx'),
  'review-form': () => import('./components/review-form.mdx'),
  'review-toolbar': () => import('./components/review-toolbar.mdx'),
  'review-pagination': () => import('./components/review-pagination.mdx'),
  'instagram-feed': () => import('./components/instagram-feed.mdx'),
  'before-after': () => import('./components/before-after.mdx'),
  'marquee': () => import('./components/marquee.mdx'),
  'collage-section': () => import('./components/collage-section.mdx'),
  'ceramics-glossary': () => import('./components/ceramics-glossary.mdx'),
  'studio-tour': () => import('./components/studio-tour.mdx'),
  'ceramics-faq': () => import('./components/ceramics-faq.mdx'),
  'page-404': () => import('./components/page-404.mdx'),
  'gift-card': () => import('./components/gift-card.mdx'),
  'policy-page': () => import('./components/policy-page.mdx'),
  'checkout-progress': () => import('./components/checkout-progress.mdx'),
};

const cache: Record<string, MdxComponent> = {};

/**
 * Returns a lazy React component for the MDX page, or null if none exists.
 */
export function getMdxPage(slug: string): MdxComponent | null {
  if (!mdxPages[slug]) return null;
  if (!cache[slug]) {
    cache[slug] = lazy(mdxPages[slug]);
  }
  return cache[slug];
}

/** Check if a component has a custom MDX page. */
export function hasMdxPage(slug: string): boolean {
  return slug in mdxPages;
}
